language: node_js
node_js:
- '14'
install:
- yarn
- yarn setup
script:
- yarn test
- yarn heroku-postbuild
deploy:
  provider: heroku
  api_key:
    secure: UkLOUZN/oXQFvjPriMwrxdNJuxvfAxOXJ4zbz/jUQT5cNXGVdYjjTGvZgKFN/lxlYagKjOcwGszfrZsWiZrGw4hSbNfefa5y+vaOqufkvLaA0s4ae8RkJCYSzkh+CV2mANV5mq+Jsj3cpRTeheRIXF/pAwj5+r+d4zQ/cXWV4r2JOVX3FZP/ltlIdnjvXEv1W6jUceYn4iEDDEvoob9rjzstMxqTS4rfIv2Cr2TYnS1cVJgdV9DnIWJLLkZ5yOEE0TPpE7XGdd0eb2H7nh4xqq2hrpTzazWBiNlIeNpTfhWB9mCgqcIN0jAWT0cSuxzqCIbFK+KRgOyBu+ydQkx/DtNSHgkqa4GOIqQjkSqx/CREoFihJ9sKm/qf+mSvtvqQMuRGDpN3Js9OBPEkDokjCLYQtEy+I/LGDQjVmQ9Y9exBR5PVJn1lR3fAL7s7nMVy0kVatzVLcq+lO0mGF9aGoKg3Lx1tToVBgBx5nLPjG0VGdLdgdESBbBKrYMJ+rVwYfNznr2LobwsTJNZJtdQhSCDhezvlVNc7mSWIKteYS/dC6DJwH65/QxDzKXB2igRDKSfPXZ+0cM4QKm7B6k8QxQ8Qflqa2vXGF3V9BPs36E1Jzl8Gm7Lu5IkK9VGTjhSODyPQdri+gSVOQvNoXz06ekN5J+uH5tKWOEQLB6YDJdc=
  app: travis-fullstack
  cleanup: true
env:
  global:
    secure: o4IibhgLIm1LhKjWkIPILzJlwo4M7DpkfP4dtxbggklHCpR/902inJ3W44aSTKaQ1vwOR1NUF22kFHOp4tGYW8XdXNepigVo90MfTvW4Xj7NQPxf4r986qme4MOvb2aqLhv5kRhcHF/l5KGIHCPVcXPbwoFzKK0mm+wIjdEwa3vk+SphTHDQFo5FRPr1IEJ+zflRKfYcyzxVECLP3TbTNt6vgSYC5y3JE6uqW1WaTtlg9imI44uaHs+7szWEgYE4xO28LnBUBSaI7fihl4qhJyya40uOQjz8MsIJOHmibDmASko16MATCH10772H6xV/PC5vdV3zisHKatiBTCulNqVJ5AQ+tb8TU+lNwbcwRye8DANi1cNOqcY5f3MAPurwrhkMueMSqBRIDIndiTBlkVQQa6aKV2aDojClXxZqI9mdOpmc9FBBStR0sc3jOlVKBuJho3SFh55PjYvO8r4KEEYzsqoa4z9mokLE9Pzet57zCVsZ0Atn0ptqmXnNYBU/KJ9+64+88COYnvk+vRMGGHinDxtBMPdwwyptBjMgwrJqzVR0hIKrWbhfjS4FWpWzXcs8svu2cpRfS32c2meDp2I8K7bLmndoIHTjULu5wCFxFFBjauZOdgGGgfI+WlhoujKJDkMyxFye/3W8Vt5mmAkZ/4cW5u+tIYS8iw1GlQI=
